# Generated by Django 6.0.2 on 2026-04-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('paciente', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('nivel_triaje', models.CharField(choices=[('CRITICO', 'Crítico (Nivel 1)'), ('EMERGENTE', 'Emergente (Nivel 2)'), ('URGENTE', 'Urgente (Nivel 3)'), ('NO_URGENTE', 'No urgente (Nivel 4)'), ('AMBULATORIO', 'Ambulatorio (Nivel 5)')], max_length=20)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('EN_ATENCION', 'En atención'), ('EN_OBSERVACION', 'En observación'), ('DADO_DE_ALTA', 'Dado de alta'), ('HOSPITALIZADO', 'Hospitalizado'), ('REFERIDO', 'Referido a otro centro'), ('CERRADO', 'Caso cerrado')], default='EN_ATENCION', max_length=20)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionUrgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.medico')),
                ('urgencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urgencia.urgencia')),
            ],
        ),
        migrations.CreateModel(
            name='AltaUrgencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('diagnostico_final', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('urgencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urgencia.urgencia')),
            ],
        ),
    ]
