# Generated by Django 6.0.2 on 2026-03-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urgencia', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_urgencia_ai
            AFTER INSERT ON urgencia_urgencia
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('urgencia', 'INSERT', NEW.id);

            CREATE TRIGGER trg_urgencia_au
            AFTER UPDATE ON urgencia_urgencia
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('urgencia', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_urgencia_ad
            AFTER DELETE ON urgencia_urgencia
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('urgencia', 'DELETE', OLD.id);


            CREATE TRIGGER trg_atencion_ai
            AFTER INSERT ON urgencia_atencionurgencia
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('atencion_urgencia', 'INSERT', NEW.id);

            CREATE TRIGGER trg_alta_ai
            AFTER INSERT ON urgencia_altaurgencia
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('alta_urgencia', 'INSERT', NEW.id);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_urgencia_ai;
            DROP TRIGGER IF EXISTS trg_urgencia_au;
            DROP TRIGGER IF EXISTS trg_urgencia_ad;
            DROP TRIGGER IF EXISTS trg_atencion_ai;
            DROP TRIGGER IF EXISTS trg_alta_ai;
            """
        )
    ]
