# Generated by Django 6.0.2 on 2026-03-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urgencia', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id);

            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER trg_urgencia_ai
            AFTER INSERT ON urgencia_urgencia
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_atencion_ai
            AFTER INSERT ON urgencia_atencionurgencia
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_alta_ai
            AFTER INSERT ON urgencia_altaurgencia
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_urgencia_ai;
            DROP TRIGGER IF EXISTS trg_atencion_ai;
            DROP TRIGGER IF EXISTS trg_alta_ai;
            """
        )
    ]
