# Generated by Django 6.0.2 on 2026-03-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("urgencia", "0002_auto_20260306_urgencia"),
    ]

    operations = [
        # Elimina triggers si existen
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_urgencia_ai ON urgencia_urgencia;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_atencion_ai ON urgencia_atencionurgencia;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_alta_ai ON urgencia_altaurgencia;"
        ),
        # Elimina la función si existe
        migrations.RunSQL("DROP FUNCTION IF EXISTS auditoria_generica() CASCADE;"),
        # Crea o reemplaza la función
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
                INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
                VALUES (
                    TG_TABLE_NAME,
                    TG_OP,
                    CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END,
                    NOW()
                );
                IF (TG_OP = 'DELETE') THEN
                    RETURN OLD;
                ELSE
                    RETURN NEW;
                END IF;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
        # Crea los triggers nuevamente
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_urgencia_ai
            AFTER INSERT ON urgencia_urgencia
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_atencion_ai
            AFTER INSERT ON urgencia_atencionurgencia
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_alta_ai
            AFTER INSERT ON urgencia_altaurgencia
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
    ]
