# Generated by Django 6.0.2 on 2026-04-04 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('URGENCIAS', 'Urgencias'), ('PEDIATRÍA', 'Pediatría'), ('OBSTETTRICIA', ' Obstetricia'), ('UCI', 'UCI'), ('HOSPITALIZACIÓN', 'Hospitalización'), ('QUIRÓFANOS', 'Quirófanos'), ('COSULTA EXTERNA', 'Consulta externa')], default='URGENCIAS', max_length=100)),
                ('tipo', models.CharField(choices=[('ATENCIÓN CRÍTICA', 'Atención crítica'), ('HOSPITALIZACIÓN', 'Hospitalización'), ('CONSULTA', 'Consulta'), ('DIAGNÓSTICO', 'Diagnóstico'), ('ADMINISTRATIVA', 'Administrativa')], default='ATENCIÓN CRÍTICA', max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('EN LIMPIEZA', 'En limpieza'), ('FUERA DE SERVICIO', 'Fuera de servicio'), ('RESERVADA', 'Reservada')], default='ACTIVA', max_length=50)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.area')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('UCI', 'UCI'), ('PEDIATRICA', 'Pediátrica'), ('AISLAMIENTO', 'Aislamiento'), ('OBSTETRICIA', 'Obstetricia')], default='GENERAL', max_length=50)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('FUERA_DE_SERVICIO', 'Fuera de servicio'), ('RESERVADA', 'Reservada'), ('EN_LIMPIEZA', 'En limpieza')], default='DISPONIBLE', max_length=50)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.habitacion')),
            ],
        ),
    ]
