# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_area_ai
            AFTER INSERT ON infraestructura_area
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('area', 'INSERT', NEW.id);

            CREATE TRIGGER trg_area_au
            AFTER UPDATE ON infraestructura_area
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('area', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_area_ad
            AFTER DELETE ON infraestructura_area
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('area', 'DELETE', OLD.id);

            CREATE TRIGGER trg_habitacion_ai
            AFTER INSERT ON infraestructura_habitacion
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('habitacion', 'INSERT', NEW.id);

            CREATE TRIGGER trg_habitacion_au
            AFTER UPDATE ON infraestructura_habitacion
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('habitacion', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_habitacion_ad
            AFTER DELETE ON infraestructura_habitacion
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('habitacion', 'DELETE', OLD.id);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_area_ai;
            DROP TRIGGER IF EXISTS trg_area_au;
            DROP TRIGGER IF EXISTS trg_area_ad;
            DROP TRIGGER IF EXISTS trg_habitacion_ai;
            DROP TRIGGER IF EXISTS trg_habitacion_au;
            DROP TRIGGER IF EXISTS trg_habitacion_ad;
            """
        )
    ]
