# Generated by Django 6.0.2 on 2026-03-22 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infraestructura', '0002_auto_20260306_infraestructura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('UCI', 'UCI'), ('PEDIATRICA', 'Pediátrica'), ('AISLAMIENTO', 'Aislamiento'), ('OBSTETRICIA', 'Obstetricia')], default='GENERAL', max_length=50)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('EN_MANTENIMIENTO', 'En mantenimiento'), ('FUERA_DE_SERVICIO', 'Fuera de servicio'), ('RESERVADA', 'Reservada'), ('EN_LIMPIEZA', 'En limpieza')], default='DISPONIBLE', max_length=50)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.habitacion')),
            ],
        ),
    ]
