# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infraestructura", "0003_cama"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Elimina el trigger si ya existe
            DROP TRIGGER IF EXISTS trg_area_ai;
            DROP TRIGGER IF EXISTS trg_habitacion_ai;

            -- Elimina la función si ya existe
            
            DROP FUNCTION IF EXISTS auditoria_generica();

            -- Crea o reemplaza la función
            
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
            INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id, NOW());

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER trg_area_ai
            AFTER INSERT ON infraestructura_area
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_habitacion_ai
            AFTER INSERT ON infraestructura_habitacion
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """,
        )
    ]
