# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_insumo_ai
            AFTER INSERT ON inventario_insumo
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('insumo', 'INSERT', NEW.id);

            CREATE TRIGGER trg_insumo_au
            AFTER UPDATE ON inventario_insumo
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('insumo', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_insumo_ad
            AFTER DELETE ON inventario_insumo
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('insumo', 'DELETE', OLD.id);

            CREATE TRIGGER trg_movimiento_ai
            AFTER INSERT ON inventario_movimientoinventario
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('movimiento_inventario', 'INSERT', NEW.id);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_insumo_ai;
            DROP TRIGGER IF EXISTS trg_insumo_au;
            DROP TRIGGER IF EXISTS trg_insumo_ad;
            DROP TRIGGER IF EXISTS trg_movimiento_ai;
            """
        )
    ]
