# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_auto_20260306_inventario"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
            INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id, now());

            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER trg_insumo_ai
            AFTER INSERT ON inventario_insumo
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_movimiento_ai
            AFTER INSERT ON inventario_movimientoinventario
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_insumo_ai;
            DROP TRIGGER IF EXISTS trg_movimiento_ai;
            """,
        )
    ]
