# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0003_auto_20260331_inventario"),
    ]

    operations = [
        # Elimina triggers si existen
        migrations.RunSQL("DROP TRIGGER IF EXISTS trg_insumo_ai ON inventario_insumo;"),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_movimiento_ai ON inventario_movimientoinventario;"
        ),
        # Elimina la función si existe
        migrations.RunSQL("DROP FUNCTION IF EXISTS auditoria_generica() CASCADE;"),
        # Crea o reemplaza la función
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
                INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
                VALUES (
                    TG_TABLE_NAME,
                    TG_OP,
                    CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END,
                    NOW()
                );
                IF (TG_OP = 'DELETE') THEN
                    RETURN OLD;
                ELSE
                    RETURN NEW;
                END IF;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
        # Crea los triggers nuevamente
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_insumo_ai
            AFTER INSERT ON inventario_insumo
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_movimiento_ai
            AFTER INSERT ON inventario_movimientoinventario
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
    ]
