# Generated by Django 6.0.2 on 2026-03-09 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('paciente', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.estudio')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.solicitudlaboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('resultados', models.TextField()),
                ('firmado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal.medico')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.solicitudlaboratorio')),
            ],
        ),
    ]
