# Generated by Django 6.0.2 on 2026-03-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_auto_20260306_laboratorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudlaboratorio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20),
        ),
    ]
