# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratorio", "0003_alter_solicitudlaboratorio_estado"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Elimina el trigger si ya existe
            DROP TRIGGER IF EXISTS trg_estudio_ai;
            DROP TRIGGER IF EXISTS trg_solicitud_ai;
            DROP TRIGGER IF EXISTS trg_resultado_ai;

            -- Elimina la función si ya existe
            
            DROP FUNCTION IF EXISTS auditoria_generica();

            -- Crea o reemplaza la función
            
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
            INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id, NOW());

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER trg_estudio_ai
            AFTER INSERT ON laboratorio_estudio
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_solicitud_ai
            AFTER INSERT ON laboratorio_solicitudlaboratorio
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_solicitud_detalle_ai
            AFTER INSERT ON laboratorio_solicituddetalle
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_resultado_ai
            AFTER INSERT ON laboratorio_resultadolaboratorio
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            """,
        )
    ]
