# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_paciente_ai
            AFTER INSERT ON paciente_paciente
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('paciente', 'INSERT', NEW.id);

            CREATE TRIGGER trg_paciente_au
            AFTER UPDATE ON paciente_paciente
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('paciente', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_paciente_ad
            AFTER DELETE ON paciente_paciente
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('paciente', 'DELETE', OLD.id);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_paciente_ai;
            DROP TRIGGER IF EXISTS trg_paciente_au;
            DROP TRIGGER IF EXISTS trg_paciente_ad;
            """
        )
    ]
