# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paciente", "0003_alter_paciente_tipo_sangre"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
            INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id, now());

            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER trg_paciente_ai
            AFTER INSERT ON paciente_paciente
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_paciente_ai;
            """,
        )
    ]
