# Generated by Django 6.0.2 on 2026-03-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
