# Generated by Django 6.0.2 on 2026-03-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_alter_auditoria_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
