# Generated by Django 6.0.2 on 2026-04-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0007_alter_auditoria_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
