# Generated by Django 6.0.2 on 2026-03-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_cita_ai
            AFTER INSERT ON cita_cita
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('cita', 'INSERT', NEW.id);

            CREATE TRIGGER trg_cita_au
            AFTER UPDATE ON cita_cita
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('cita', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_cita_ad
            AFTER DELETE ON cita_cita
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('cita', 'DELETE', OLD.id);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_cita_ai;
            DROP TRIGGER IF EXISTS trg_cita_au;
            DROP TRIGGER IF EXISTS trg_cita_ad;
            """
        )
    ]
