# Generated by Django 6.0.2 on 2026-03-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cita", "0002_auto_20260306_cita"),
    ]

    operations = [
        # Elimina el trigger si existe
        migrations.RunSQL("DROP TRIGGER IF EXISTS trg_cita_ai ON cita_cita;"),
        # Elimina la función si existe
        migrations.RunSQL("DROP FUNCTION IF EXISTS auditoria_generica() CASCADE;"),
        # Crea o reemplaza la función
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
                INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
                VALUES (TG_TABLE_NAME, TG_OP, NEW.id, NOW());
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
        # Crea el trigger nuevamente
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_cita_ai
            AFTER INSERT ON cita_cita
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
    ]
