# Generated by Django 6.0.2 on 2026-03-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id, now());

            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER trg_factura_ai
            AFTER INSERT ON facturacion_factura
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_factura_detalle_ai
            AFTER INSERT ON facturacion_facturadetalle
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            
            CREATE TRIGGER trg_pago_ai
            AFTER INSERT ON facturacion_pago
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_factura_ai;
            DROP TRIGGER IF EXISTS trg_factura_detalle_ai;
            DROP TRIGGER IF EXISTS trg_pago_ai;
            """
        )
    ]
