# Generated by Django 6.0.2 on 2026-03-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_factura_ai
            AFTER INSERT ON facturacion_factura
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('factura', 'INSERT', NEW.id);

            CREATE TRIGGER trg_factura_au
            AFTER UPDATE ON facturacion_factura
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('factura', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_factura_ad
            AFTER DELETE ON facturacion_factura
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('factura', 'DELETE', OLD.id);

            CREATE TRIGGER trg_factura_detalle_ai
            AFTER INSERT ON facturacion_facturadetalle
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('factura_detalle', 'INSERT', NEW.id);

            CREATE TRIGGER trg_factura_detalle_ad
            AFTER DELETE ON facturacion_facturadetalle
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('factura_detalle', 'DELETE', OLD.id);

            CREATE TRIGGER trg_pago_ai
            AFTER INSERT ON facturacion_pago
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('pago', 'INSERT', NEW.id);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_factura_ai;
            DROP TRIGGER IF EXISTS trg_factura_au;
            DROP TRIGGER IF EXISTS trg_factura_ad;
            DROP TRIGGER IF EXISTS trg_factura_detalle_ai;
            DROP TRIGGER IF EXISTS trg_factura_detalle_ad;
            DROP TRIGGER IF EXISTS trg_pago_ai;
            """
        )
    ]
