# Generated by Django 6.0.2 on 2026-03-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_auto_20260306_facturacion'),
        ('laboratorio', '0003_alter_solicitudlaboratorio_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorio.solicitudlaboratorio'),
        ),
    ]
