# Generated by Django 6.0.2 on 2026-03-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_factura_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='origen_estudio',
            field=models.BooleanField(default=False),
        ),
    ]
