# Generated by Django 6.0.2 on 2026-03-23 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_factura_origen_estudio'),
        ('farmacia', '0003_dispensaciondetalle'),
        ('infraestructura', '0003_cama'),
        ('laboratorio', '0003_alter_solicitudlaboratorio_estado'),
        ('paciente', '0003_alter_paciente_tipo_sangre'),
        ('urgencia', '0002_auto_20260306_urgencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('facturado', models.BooleanField(default=False)),
                ('cama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infraestructura.cama')),
                ('dispensacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.dispensacion')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='facturacion.factura')),
                ('laboratorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='laboratorio.solicitudlaboratorio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('urgencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='urgencia.urgencia')),
            ],
        ),
    ]
