# Generated by Django 6.0.2 on 2026-04-02 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_auto_20260331_facturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturadetalle',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura'),
        ),
    ]
