# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_medico_ai
            AFTER INSERT ON personal_medico
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('medico', 'INSERT', NEW.id);

            CREATE TRIGGER trg_medico_au
            AFTER UPDATE ON personal_medico
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('medico', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_medico_ad
            AFTER DELETE ON personal_medico
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('medico', 'DELETE', OLD.id);

            CREATE TRIGGER trg_enfermero_ai
            AFTER INSERT ON personal_enfermero
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('enfermero', 'INSERT', NEW.id);

            CREATE TRIGGER trg_enfermero_au
            AFTER UPDATE ON personal_enfermero
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('enfermero', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_enfermero_ad
            AFTER DELETE ON personal_enfermero
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('enfermero', 'DELETE', OLD.id);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_medico_ai;
            DROP TRIGGER IF EXISTS trg_medico_au;
            DROP TRIGGER IF EXISTS trg_medico_ad;
            DROP TRIGGER IF EXISTS trg_enfermero_ai;
            DROP TRIGGER IF EXISTS trg_enfermero_au;
            DROP TRIGGER IF EXISTS trg_enfermero_ad;
            """
        )
    ]
