# Generated by Django 6.0.2 on 2026-04-05 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermero',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('area', models.CharField(choices=[('laboratorio', 'Laboratorio'), ('sistemas', 'Sistemas'), ('administracion', 'Administración'), ('farmacia', 'Farmacia'), ('mantenimiento', 'Mantenimiento'), ('direccion', 'Dirección')], max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='hospital.hospital')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
