# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0002_auto_20260306_personal"),
    ]

    operations = [
        migrations.RunSQL(
            """
            -- Elimina el trigger si ya existe
            DROP TRIGGER IF EXISTS trg_medico_ai;
            DROP TRIGGER IF EXISTS trg_enfermero_ai;

            -- Elimina la función si ya existe
            
            DROP FUNCTION IF EXISTS auditoria_generica();

            -- Crea o reemplaza la función
            
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
            INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id, NOW());

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER trg_medico_ai
            AFTER INSERT ON personal_medico
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            
            CREATE TRIGGER trg_enfermero_ai
            AFTER INSERT ON personal_enfermero
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """,
        )
    ]
