# Generated by Django 6.0.2 on 2026-03-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_turno_ai
            AFTER INSERT ON turno_turno
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('turno', 'INSERT', NEW.id);

            CREATE TRIGGER trg_turno_au
            AFTER UPDATE ON turno_turno
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('turno', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_turno_ad
            AFTER DELETE ON turno_turno
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('turno', 'DELETE', OLD.id);

            CREATE TRIGGER trg_turno_personal_ai
            AFTER INSERT ON turno_turnopersonal
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('turno_personal', 'INSERT', NEW.id);

            CREATE TRIGGER trg_turno_personal_au
            AFTER UPDATE ON turno_turnopersonal
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('turno_personal', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_turno_personal_ad
            AFTER DELETE ON turno_turnopersonal
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('turno_personal', 'DELETE', OLD.id);

            CREATE TRIGGER trg_asistencia_ai
            AFTER INSERT ON turno_asistencia
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('asistencia', 'INSERT', NEW.id);

            CREATE TRIGGER trg_asistencia_au
            AFTER UPDATE ON turno_asistencia
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('asistencia', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_asistencia_ad
            AFTER DELETE ON turno_asistencia
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('asistencia', 'DELETE', OLD.id);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_turno_ai;
            DROP TRIGGER IF EXISTS trg_turno_au;
            DROP TRIGGER IF EXISTS trg_turno_ad;
            DROP TRIGGER IF EXISTS trg_turno_personal_ai;
            DROP TRIGGER IF EXISTS trg_turno_personal_au;
            DROP TRIGGER IF EXISTS trg_turno_personal_ad;
            DROP TRIGGER IF EXISTS trg_asistencia_ai;
            DROP TRIGGER IF EXISTS trg_asistencia_au;
            DROP TRIGGER IF EXISTS trg_asistencia_ad;
            """
        )
    ]
