# Generated by Django 6.0.2 on 2026-03-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turno', '0002_auto_20260306_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
