# Generated by Django 6.0.2 on 2026-03-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("turno", "0005_auto_20260331_turno"),
    ]

    operations = [
        # Elimina triggers si existen
        migrations.RunSQL("DROP TRIGGER IF EXISTS trg_turno_ai ON turno_turno;"),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_turno_personal_ai ON turno_turnopersonal;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_asistencia_ai ON turno_asistencia;"
        ),
        # Elimina la función si existe
        migrations.RunSQL("DROP FUNCTION IF EXISTS auditoria_generica() CASCADE;"),
        # Crea o reemplaza la función
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
                INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
                VALUES (
                    TG_TABLE_NAME,
                    TG_OP,
                    CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END,
                    NOW()
                );
                IF (TG_OP = 'DELETE') THEN
                    RETURN OLD;
                ELSE
                    RETURN NEW;
                END IF;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
        # Crea los triggers nuevamente
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_turno_ai
            AFTER INSERT OR UPDATE OR DELETE ON turno_turno
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_turno_personal_ai
            AFTER INSERT OR UPDATE OR DELETE ON turno_turnopersonal
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_asistencia_ai
            AFTER INSERT OR UPDATE OR DELETE ON turno_asistencia
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
    ]
