# Generated by Django 6.0.2 on 2026-04-04 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('PACIENTES', 'Pacientes'), ('LABORATORIO', 'Laboratorio'), ('HISTORIAL CLINICO', 'Historial Clinico'), ('INVENTARIOS', 'Inventarios'), ('FACTURACIÓN', 'Facturación'), ('URGENCIAS', 'Urgencias'), ('HOSPITALIZACIÓN', 'Hospitalización'), ('INFRAESTRUCTURA', 'Ingfraestructura'), ('ADMINISTRACIÓN', 'Administración'), ('TURNOS', 'Turnos'), ('SISTEMAS', 'Sisitemas')], default='PACIENTES', max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('MÉDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('LABORATORO', 'Laboratorio'), ('FARMACIA', 'Farmacia'), ('ADMINISTRACIÓN', 'Administración'), ('URGENCIAS', 'Urgencias'), ('MANTENIMIENTO', 'Mantenimiento'), ('SISTEMAS', 'Sistemas'), ('DIRECCIÓN', 'Dirección')], default='MÉDICO', max_length=70)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.rol')),
            ],
            options={
                'verbose_name': 'Rol y permiso',
                'verbose_name_plural': 'Roles y permisos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Hospital',
                'verbose_name_plural': 'Usuarios de Hospitales',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario y Rol',
                'verbose_name_plural': 'Usuarios y Roles',
            },
        ),
    ]
