# Generated by Django 6.0.2 on 2026-03-09 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('1. PERMISOS DEL MÓDULO DE PACIENTES', '1. Permisos del módulo de Pacientes'), ('VER PACIENTES', 'Ver pacientes'), ('CREAR PACIENTES', 'Crear pacientes'), ('EDITAR PACIENTES', 'Editar pacientes'), ('ELIMINAR PACIENTES', 'Eliminar pacientes'), ('VER HISTORIAL CLÍNICO', 'Ver historial clínico'), ('EDITAR HISTORIAL CLÍNICO', 'Editar historial clínico'), ('VER ALERGIAS', 'Ver alergias'), ('EDITAR ALERGIAS', 'Editar alergias'), ('2. PERMISOS DEL MÓDULO DE LABORATORIO', '2. Permisos del módulo de Laboratorio'), ('VER ÓRDENES DE LABORATORIO', 'Ver órdenes de laboratorio'), ('CREAR ÓRDENES', 'Crear órdenes'), ('EDITAR ÓRDENES', 'Editar órdenes'), ('REGISTRAR RESULTADOS', 'Registrar resultados'), ('VALIDAR RESULTADOS', 'Validar resultados'), ('IMPRIMIR RESULTADOS', 'Imprimir resultados'), ('3. PERMISOS DEL MÓDULO DE FARMACIA', '3. Permisos del módulo de Farmacia'), ('VER MEDICAMENTOS', 'Ver medicamentos'), ('REGISTRAR ENTRADAS', 'Registrar entradas'), ('REGISTRAR SALIDAS', 'Registrar salidas'), ('DISPENSAR MEDICAMENTOS', 'Dispensar medicamentos'), ('AJUSTAR INVENTARIO', 'Ajustar inventario'), ('VER INVENTARIO CRÍTICO', 'Ver inventario crítico'), ('4. PERMISOS DEL MÓDULO DE FACTURACIÓN / CAJA', '4. Permisos del módulo de Facturación / Caja'), ('CREAR FACTURAS', 'Crear facturas'), ('EDITAR FACTURAS', 'Editar facturas'), ('CANCELAR FACTURAS', 'Cancelar facturas'), ('REGISTRAR PAGOS', 'Registrar pagos'), ('VER REPORTES DE INGRESOS', 'Ver reportes de ingresos'), ('5. PERMISOS DEL MÓDULO DE URGENCIAS', '5. Permisos del módulo de Urgencias'), ('REGISTRAR TRIAGE', 'Registrar triage'), ('REGISTRAR ATENCIÓN INICIAL', ' Registrar atención inicial'), ('REGISTRAR EVOLUCIÓN', 'Registrar evolución'), ('CERRAR CASO DE URGENCIAS', 'Cerrar caso de urgencias'), ('6. PERMISOS DEL MÓDULO DE HOSPITALIZACIÓN', '6. Permisos del módulo de Hospitalización'), ('ASIGNAR CAMA', 'Asignar cama'), ('CAMBIAR CAMA', 'Cambiar cama'), ('REGISTRAR NOTAS DE ENFERMERÍA', 'Registrar notas de enfermería'), ('REGISTRAR SIGNOS VITALES', 'Registrar signos vitales'), ('REGISTRAR EVOLUCIÓN MÉDICA', 'Registrar evolución médica'), ('7. PERMISOS DEL MÓDULO DE MANTENIMIENTO', '7. Permisos del módulo de Mantenimiento'), ('REGISTRAR INCIDENCIAS', 'Registrar incidencias'), ('ASIGNAR TÉCNICOS', 'Asignar técnicos'), ('CERRAR INCIDENCIAS', 'Cerrar incidencias'), ('VER HISTORIAL DE MANTENIMIENTO', 'Ver historial de mantenimiento'), ('8. PERMISOS ADMINISTRATIVOS', '8. Permisos administrativos'), ('VER USUARIOS', 'Ver usuarios'), ('CREAR USUARIOS', 'Crear usuarios'), ('EDITAR USUARIOS', 'Editar usuarios'), ('DESACTIVAR USUARIOS', 'Desactivar usuarios'), ('ASIGNAR ROLES', 'Asignar roles'), ('VER AUDITORÍA', 'Ver auditoría'), ('VER LOGS DEL SISTEMA', ' Ver logs del sistema'), ('9. PERMISOS DEL ÁREA DE SISTEMAS', '9. Permisos del área de Sistemas'), ('ADMINISTRAR SERVIDORES', 'Administrar servidores'), ('ADMINISTRAR RESPALDOS', 'Administrar respaldos'), ('ADMINISTRAR CONFIGURACIÓN DEL SISTEMA', 'Administrar configuración del sistema'), ('ADMINISTRAR PERMISOS', 'Administrar permisos'), ('ADMINISTRAR ROLES', 'Administrar roles')], default='1. PERMISOS DEL MÓDULO DE PACIENTES', max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('1. ÁREA MÉDICA (CLÍNICA)', '1. Área Médica (Clínica)'), ('MÉDICO GENERAL', 'Médico general'), ('MÉDICO ESPECIALISTA (CARDIÓLOGO, PEDIATRA, INTERNISTA, ETC.)', 'Médico especialista (cardiólogo, pediatra, internista, etc.)'), ('CIRUJANO', 'Cirujano'), ('ANESTESIÓLOGO', 'Anestesiólogo'), ('RESIDENTE', 'Residente'), ('INTERNO', 'Interno'), ('PASANTE DE MEDICINA', 'Pasante de medicina'), ('JEFE DE SERVICIO', 'Jefe de servicio'), ('DIRECTOR MÉDICO', 'Director Médico'), ('2. ÁREA DE ENFERMERÍA', '2. Área de Enfermería'), ('ENFERMERA GENERAL', 'Enfermera general'), ('ENFERMERA ESPECIALISTA (QUIRÓFANO, UCI, PEDIATRÍA…)', 'Enfermera especialista (quirófano, UCI, pediatría…)'), ('ENFERMERA JEFE / SUPERVISORA', 'Enfermera Jefe / supervisora'), ('AUXILIAR DE ENFERMERÍA', 'Auxiliar de enfermería'), ('CAMILLERO', 'Camillero'), ('3. ÁREA DE DIAGNÓSTICO Y LABORATORIO', '3. Área de Diagnóstico y Laboratorio'), ('TÉCNICO LABORATORISTA', 'Técnico laboratorista'), ('QUÍMICO CLÍNICO', 'Químico clínico'), ('RADIÓLOGO', 'Radiólogo'), ('TÉCNICO EN IMAGENOLOGÍA', 'Técnico en imagenología'), ('PATÓLOGO', 'Patólogo'), ('4. ÁREA DE FARMACIA', '4. Área de Farmacia'), ('CONTROL DE MEDICAMENTOS:', 'Control de medicamentos:'), ('FARMACÉUTICO', 'Farmacéutico'), ('AUXILIAR DE FARMACIA', 'Auxiliar de farmacia'), ('ENCARGADO DE INVENTARIO DE MEDICAMENTOS', 'Encargado de inventario de medicamentos'), ('5. ÁREA ADMINISTRATIVA', '5. Área Administrativa'), ('RECEPCIONISTA', 'Recepcionista'), ('CAJERO', 'Cajero'), ('FACTURACIÓN', 'Facturación'), ('ADMISIÓN', 'Admisión'), ('ARCHIVO CLÍNICO', 'Archivo clínico'), ('RECURSOS HUMANOS', 'Recursos humanos'), ('COMPRAS', 'Compras'), ('CONTABILIDAD', 'Contabilidad'), (' AUDITOR INTERNO', 'Auditor Interno'), ('6. ÁREA DE EMERGENCIAS', '6. Área de Emergencias'), ('PARAMÉDICO', 'Paramédico'), ('TÉCNICO EN URGENCIAS MÉDICAS', 'Técnico en urgencias médicas'), ('COORDINADOR DE EMERGENCIAS', 'Coordinador de emergencias'), ('7. ÁREA DE MANTENIMIENTO E INFRAESTRUCTURA', '7. Área de Mantenimiento e Infraestructura'), ('PARA QUE EL HOSPITAL FUNCIONE FÍSICAMENTE:', 'Para que el hospital funcione físicamente:'), ('TÉCNICO DE MANTENIMIENTO', 'Técnico de mantenimiento'), ('ELECTRICISTA', 'Electricista'), ('PLOMERO', 'Plomero'), ('PERSONAL DE LIMPIEZA', 'Personal de limpieza'), ('SEGURIDAD', 'Seguridad'), ('8. ÁREA DE SISTEMAS / TI', '8. Área de Sistemas / TI'), ('ADMINISTRADOR DE SISTEMAS', 'Administrador de sistemas'), ('TÉCNICO DE SOPORTE', 'Técnico de soporte'), ('INGENIERO DE REDES', 'Ingeniero de redes'), ('ADMINISTRADOR DE BASE DE DATOS', 'Administrador de base de datos'), ('ESPECIALISTA EN SEGURIDAD INFORMÁTICA', 'especialista en Seguridad informática'), ('9. DIRECCIÓN Y GESTIÓN', '9. Dirección y Gestión'), ('DIRECTOR GENERAL', 'Director general'), ('SUBDIRECTOR', 'Subdirector'), ('GERENTE ADMINISTRATIVO', 'Gerente administrativo'), ('COMITÉ DE CALIDAD', 'Comité de calidad'), ('COMITÉ DE ÉTICA', 'Comité de ética')], default='1. ÁREA MÉDICA (CLÍNICA)', max_length=70)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('ELIMINADO', 'Eliminado')], default='ACTIVO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.permiso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.rol')),
            ],
            options={
                'verbose_name': 'Rol y permiso',
                'verbose_name_plural': 'Roles y permisos',
            },
        ),
        migrations.CreateModel(
            name='UsuarioHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de Hospital',
                'verbose_name_plural': 'Usuarios de Hospitales',
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acceso.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario y Rol',
                'verbose_name_plural': 'Usuarios y Roles',
            },
        ),
    ]
