# Generated by Django 6.0.2 on 2026-04-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('MÉDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('LABORATORIO', 'Laboratorio'), ('FARMACIA', 'Farmacia'), ('ADMINISTRACIÓN', 'Administración'), ('URGENCIAS', 'Urgencias'), ('MANTENIMIENTO', 'Mantenimiento'), ('SISTEMAS', 'Sistemas'), ('DIRECCIÓN', 'Dirección')], default='MÉDICO', max_length=70),
        ),
    ]
