# Generated by Django 6.0.2 on 2026-03-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_rol_ai
            AFTER INSERT ON acceso_rol
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('rol', 'INSERT', NEW.id);

            CREATE TRIGGER trg_rol_au
            AFTER UPDATE ON acceso_rol
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('rol', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_rol_ad
            AFTER DELETE ON acceso_rol
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('rol', 'DELETE', OLD.id);

            CREATE TRIGGER trg_permiso_ai
            AFTER INSERT ON acceso_permiso
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('permiso', 'INSERT', NEW.id);

            CREATE TRIGGER trg_permiso_au
            AFTER UPDATE ON acceso_permiso
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('permiso', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_permiso_ad
            AFTER DELETE ON acceso_permiso
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('permiso', 'DELETE', OLD.id);

            CREATE TRIGGER trg_usuario_ai
            AFTER INSERT ON acceso_usuario
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('usuario', 'INSERT', NEW.id);

            CREATE TRIGGER trg_usuario_au
            AFTER UPDATE ON acceso_usuario
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('usuario', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_usuario_ad
            AFTER DELETE ON acceso_usuario
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('usuario', 'DELETE', OLD.id);

            CREATE TRIGGER trg_usuario_rol_ai
            AFTER INSERT ON acceso_usuariorol
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('usuario_rol', 'INSERT', NEW.id);

            CREATE TRIGGER trg_usuario_rol_ad
            AFTER DELETE ON acceso_usuariorol
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('usuario_rol', 'DELETE', OLD.id);

            CREATE TRIGGER trg_rol_permiso_ai
            AFTER INSERT ON acceso_rolpermiso
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('rol_permiso', 'INSERT', NEW.id);

            CREATE TRIGGER trg_rol_permiso_ad
            AFTER DELETE ON acceso_rolpermiso
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('rol_permiso', 'DELETE', OLD.id);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_rol_ai;
            DROP TRIGGER IF EXISTS trg_rol_au;
            DROP TRIGGER IF EXISTS trg_rol_ad;
            DROP TRIGGER IF EXISTS trg_permiso_ai;
            DROP TRIGGER IF EXISTS trg_permiso_au;
            DROP TRIGGER IF EXISTS trg_permiso_ad;
            DROP TRIGGER IF EXISTS trg_usuario_ai;
            DROP TRIGGER IF EXISTS trg_usuario_au;
            DROP TRIGGER IF EXISTS trg_usuario_ad;
            DROP TRIGGER IF EXISTS trg_usuario_rol_ai;
            DROP TRIGGER IF EXISTS trg_usuario_rol_au;
            DROP TRIGGER IF EXISTS trg_usuario_rol_ad;
            DROP TRIGGER IF EXISTS trg_rol_permiso_ai;
            DROP TRIGGER IF EXISTS trg_rol_permiso_ad;
            """
        )

    ]
