# Generated by Django 6.0.2 on 2026-03-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id, now());

            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER trg_rol_ai
            AFTER INSERT ON acceso_rol
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            
            CREATE TRIGGER trg_permiso_ai
            AFTER INSERT ON acceso_permiso
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_usuario_ai
            AFTER INSERT ON acceso_usuario
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_usuario_rol_ai
            AFTER INSERT ON acceso_usuariorol
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_rol_permiso_ai
            AFTER INSERT ON acceso_rolpermiso
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_rol_ai;
            DROP TRIGGER IF EXISTS trg_permiso_ai;
            DROP TRIGGER IF EXISTS trg_usuario_ai;
            DROP TRIGGER IF EXISTS trg_usuario_rol_ai;
            DROP TRIGGER IF EXISTS trg_rol_permiso_ai;
            """
        )

    ]
