# Generated by Django 6.0.2 on 2026-04-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_alter_rol_nombre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('usuario', 'rol')},
        ),
    ]
