# Generated by Django 6.0.2 on 2026-03-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0002_auto_20260306_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
