# Generated by Django 6.0.2 on 2026-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0003_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(choices=[('PACIENTES', 'Pacientes'), ('LABORATORIO', 'Laboratorio'), ('INVENTARIOS', 'Inventarios'), ('FACTURACIÓN', 'Facturación'), ('URGENCIAS', 'Urgencias'), ('HOSPITALIZACIÓN', 'Hospitalización'), ('MANTENIMIENTO', 'Mantenimiento'), ('ADMINISTRACIÓN', 'Administración'), ('SISTEMAS', 'Sisitemas')], default='PACIENTES', max_length=100),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('MÉDICO', 'Médico'), ('ENFERMERO', 'Enfermero'), ('LABORATORO', 'Laboratorio'), ('FARMACIA', 'Farmacia'), ('ADMINISTRACIÓN', 'Administración'), ('URGENCIAS', 'Urgencias'), ('MANTENIMIENTO', 'Mantenimiento'), ('SISTEMAS', 'Sistemas'), ('DIRECCIÓN', 'Dirección')], default='MÉDICO', max_length=70),
        ),
    ]
