# Generated by Django 6.0.2 on 2026-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0004_alter_permiso_nombre_alter_rol_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(choices=[('PACIENTES', 'Pacientes'), ('LABORATORIO', 'Laboratorio'), ('HISTORIAL CLINICO', 'Historial Clinico'), ('INVENTARIOS', 'Inventarios'), ('FACTURACIÓN', 'Facturación'), ('URGENCIAS', 'Urgencias'), ('HOSPITALIZACIÓN', 'Hospitalización'), ('INFRAESTRUCTURA', 'Ingfraestructura'), ('ADMINISTRACIÓN', 'Administración'), ('TURNOS', 'Turnos'), ('SISTEMAS', 'Sisitemas')], default='PACIENTES', max_length=100),
        ),
    ]
