# Generated by Django 6.0.2 on 2026-03-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acceso", "0005_alter_permiso_nombre"),
    ]

    operations = [
        # Elimina triggers si existen
        migrations.RunSQL("DROP TRIGGER IF EXISTS trg_rol_ai ON acceso_rol;"),
        migrations.RunSQL("DROP TRIGGER IF EXISTS trg_permiso_ai ON acceso_permiso;"),
        migrations.RunSQL("DROP TRIGGER IF EXISTS trg_usuario_ai ON acceso_usuario;"),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_usuario_rol_ai ON acceso_usuariorol;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_rol_permiso_ai ON acceso_rolpermiso;"
        ),
        # Elimina la función si existe
        migrations.RunSQL("DROP FUNCTION IF EXISTS auditoria_generica() CASCADE;"),
        # Crea o reemplaza la función
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
                INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
                VALUES (
                    TG_TABLE_NAME,
                    TG_OP,
                    CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END,
                    NOW()
                );
                IF (TG_OP = 'DELETE') THEN
                    RETURN OLD;
                ELSE
                    RETURN NEW;
                END IF;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
        # Crea los triggers nuevamente
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_rol_ai
            AFTER INSERT ON acceso_rol
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_permiso_ai
            AFTER INSERT ON acceso_permiso
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_usuario_ai
            AFTER INSERT ON acceso_usuario
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_usuario_rol_ai
            AFTER INSERT ON acceso_usuariorol
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_rol_permiso_ai
            AFTER INSERT ON acceso_rolpermiso
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
    ]
