# Generated by Django 6.0.2 on 2026-03-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id);

            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql
            
            CREATE TRIGGER trg_medicamento_ai
            AFTER INSERT ON farmacia_medicamento
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_receta_ai
            AFTER INSERT ON farmacia_receta
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            
            CREATE TRIGGER trg_receta_detalle_ai
            AFTER INSERT ON farmacia_recetadetalle
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();

            CREATE TRIGGER trg_dispensacion_ai
            AFTER INSERT ON farmacia_dispensacion
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_medicamento_ai;
            DROP TRIGGER IF EXISTS trg_receta_ai;
            DROP TRIGGER IF EXISTS trg_receta_detalle_ai;
            DROP TRIGGER IF EXISTS trg_dispensacion_ai;
            """
        )
    ]
