# Generated by Django 6.0.2 on 2026-03-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmacia", "0003_dispensaciondetalle"),
    ]

    operations = [
        # Elimina triggers si existen
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_medicamento_ai ON farmacia_medicamento;"
        ),
        migrations.RunSQL("DROP TRIGGER IF EXISTS trg_receta_ai ON farmacia_receta;"),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_receta_detalle_ai ON farmacia_recetadetalle;"
        ),
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_dispensacion_ai ON farmacia_dispensacion;"
        ),
        # Elimina la función si existe
        migrations.RunSQL("DROP FUNCTION IF EXISTS auditoria_generica() CASCADE;"),
        # Crea o reemplaza la función
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
                INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
                VALUES (
                    TG_TABLE_NAME,
                    TG_OP,
                    CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END,
                    NOW()
                );
                IF (TG_OP = 'DELETE') THEN
                    RETURN OLD;
                ELSE
                    RETURN NEW;
                END IF;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
        # Crea los triggers nuevamente
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_medicamento_ai
            AFTER INSERT ON farmacia_medicamento
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_receta_ai
            AFTER INSERT ON farmacia_receta
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_receta_detalle_ai
            AFTER INSERT ON farmacia_recetadetalle
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_dispensacion_ai
            AFTER INSERT ON farmacia_dispensacion
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
    ]
