# Generated by Django 6.0.2 on 2026-03-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_usuario_hospital_ai
            AFTER INSERT ON hospital_hospital
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('usuario_hospital', 'INSERT', NEW.id);

            CREATE TRIGGER trg_usuario_hospital_ad
            AFTER DELETE ON hospital_hospital
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('usuario_hospital', 'DELETE', OLD.id);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_hospital_ai;
            DROP TRIGGER IF EXISTS trg_hosptal_ad;
            """
        )
    ]
