# Generated by Django 6.0.2 on 2026-03-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_auto_20260306_hospital"),
    ]

    operations = [
        # Elimina el trigger si existe
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_hospital_ai ON hospital_hospital;"
        ),
        # Elimina la función si existe
        migrations.RunSQL("DROP FUNCTION IF EXISTS auditoria_generica();"),
        # Crea o reemplaza la función
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
                INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
                VALUES (TG_TABLE_NAME, TG_OP, NEW.id, NOW());
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
        # Crea el trigger nuevamente
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_usuario_hospital_ai
            AFTER INSERT ON hospital_hospital
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
    ]
