# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
         migrations.RunSQL(
            """
            CREATE TRIGGER trg_historial_ai
            AFTER INSERT ON historial_historialclinico
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('historial_clinico', 'INSERT', NEW.id);

            CREATE TRIGGER trg_historial_au
            AFTER UPDATE ON historial_historialclinico
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('historial_clinico', 'UPDATE', NEW.id);

            CREATE TRIGGER trg_historial_ad
            AFTER DELETE ON historial_historialclinico
            FOR EACH ROW
            INSERT INTO auditoria(tabla, operacion, registro_id)
            VALUES ('historial_clinico', 'DELETE', OLD.id);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_historial_ai;
            DROP TRIGGER IF EXISTS trg_historial_au;
            DROP TRIGGER IF EXISTS trg_historial_ad;
            """
        )
    ]
