# Generated by Django 6.0.2 on 2026-03-17 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0002_auto_20260306_cita'),
        ('historial', '0002_auto_20260306_historial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialclinico',
            name='cita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cita.cita'),
        ),
    ]
