# Generated by Django 6.0.2 on 2026-03-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("historial", "0003_historialclinico_cita"),
    ]

    operations = [
        # Elimina el trigger si existe
        migrations.RunSQL(
            "DROP TRIGGER IF EXISTS trg_historial_ai ON historial_historialclinico;"
        ),
        # Elimina la función si existe
        migrations.RunSQL("DROP FUNCTION IF EXISTS auditoria_generica() CASCADE;"),
        # Crea o reemplaza la función
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
                INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
                VALUES (TG_TABLE_NAME, TG_OP, NEW.id, NOW());
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        ),
        # Crea el trigger nuevamente
        migrations.RunSQL(
            """
            CREATE TRIGGER trg_historial_ai
            AFTER INSERT ON historial_historialclinico
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """
        ),
    ]
