# Generated by Django 6.0.2 on 2026-03-22 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0003_alter_paciente_tipo_sangre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('uci', 'UCI'), ('aislamiento', 'Aislamiento'), ('pediatrica', 'Pediátrica')], default='general', max_length=20)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('mantenimiento', 'Mantenimiento')], default='libre', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('piso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.cama')),
            ],
            options={
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.AddField(
            model_name='cama',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalizacion.habitacion'),
        ),
    ]
