# Generated by Django 6.0.2 on 2026-03-22 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalizacion', '0001_initial'),
        ('infraestructura', '0003_cama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cama',
            name='habitacion',
        ),
        migrations.AlterField(
            model_name='asignacioncama',
            name='cama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.cama'),
        ),
        migrations.DeleteModel(
            name='Habitacion',
        ),
        migrations.DeleteModel(
            name='Cama',
        ),
    ]
