# Generated by Django 6.0.2 on 2026-03-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hospital", "0002_remove_cama_habitacion_alter_asignacioncama_cama_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            """
            
            CREATE OR REPLACE FUNCTION auditoria_generica()
            RETURNS TRIGGER AS $$
            BEGIN
            INSERT INTO auditoria(tabla, operacion, registro_id, fecha)
            VALUES (TG_TABLE_NAME, TG_OP, NEW.id, now());

            RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            
            CREATE TRIGGER trg_asignacioncama
            AFTER INSERT ON hospitalizacion_asignacioncama
            FOR EACH ROW
            EXECUTE FUNCTION auditoria_generica();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_asignacioncama;
            """,
        )
    ]
